spring:
  datasource:
    url: jdbc:mysql://localhost/test?serverTimezone=UTC
    username: root
    password: 5418
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#     ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
logging:
  level:
    org.hibernate.SQL: debug #로거를 통해서 로그를 찍는다.
#    org.hibernate.type: trace

# org.hibernate.type: trace